### ISSUE TITLE
reasons behind limiting it to 100 element

### ISSUE THREAD

**Issue by azaiter** [xcatliu/grubbs#2]
Is there any statistical reason behind limiting the library to only accept a max of 100 elements?

**Comment by xcatliu** [comment]
Yes there is. The Grubbs' critical value table only have values for N < 100
http://www.sediment.uni-goettingen.de/staff/dunkl/software/pep-grubbs.pdf

**Comment by azaiter** [comment]
Thank you for the response and info, that's sufficient. Closed.
